openzim/youtube

youtube2zim/entrypoint.py, youtube2zim/scraper.py
Fixes #31 
- Allow user to add a parameter to filter and download videos uploaded on or after the specified date.
- Used `youtube_dl.DateRange` to specify daterange
- Used Youtube API to get published date
=> Add feature to filter videos by date

CHANGELOG, youtube2zim/scraper.py
Requested format for videos was `webm` or `mp4` based on user selection.
This used to be fine as most videos would return a usable video for both format or
fallback and convert to the requested format.
Recently, Youtube changed and seems to not offer video with audio option for `webm`.
As `webm` is also used for audio, Youtube-dl would consider this a video-only webm
request, given the available formats.
This resulted in all videos being silently without audio.
This fixes it by specifically requesting the best available audio+video for `format` and if
not available would request and merge separate files for both and if still not, would
request the best available video+audio and convert it as before
=> Fixed #70: change requested formats

CHANGELOG, CONTRIBUTING.md, setup.py, youtube2zim/converter.py, youtube2zim/reencode_low_quality.py, youtube2zim/scraper.py
#71 introduces a regression on `--low-quality` as our processing (recompression) was launched using the youtube_dl progress hook.
This PR solves it by splitting the hook into dedicated functions and launching it after youtube_dl has completed the video download.
This should also help in transitioning to #72
=> Fix low quality

youtube2zim/scraper.py
Although unlikely, should we get a video without a channel (no entry for the videoId
in the videos_channels JSON), process would crash when writing the HTML page (at the
very end of the task).
Instead, we filter out those videos.
@satyamtg could you please take a look at this? Followed your diagnostic and suggestion on #76. Should not happen but should it, let's skip it.
=> Fixed #76: filter out videos without channel

CHANGELOG, requirements.txt, youtube2zim/converter.py, youtube2zim/reencode_low_quality.py, youtube2zim/scraper.py
* Fixes #75 by adding `max_muxing_queue_size` to FFmpeg args.
* removes old code for recompressing in high quality (unused)
* better variable names for triggering this
* better wording for S3 logs
=> Clearer recompress handling

youtube2zim/templates/article.html, youtube2zim/templates/assets/app.js
Fixes #54 by not displaying PIP toggle if its not supported by the browser. Tested on kiwix-serve versions and Kiwix desktop on Windows and Linux.
@rgaudin could you please confirm if this works on Safari on MacOS?
=> Fixes #54 - Hide picture-in-picture toggle

CHANGELOG, README.md, setup.py, youtube2zim/playlists/__main__.py, youtube2zim/playlists/entrypoint.py, youtube2zim/playlists/scraper.py, youtube2zim/scraper.py, youtube2zim/utils.py, youtube2zim/youtube.py
Here's a simpler approach to implementing #93 .
Instead of reimplementing all arguments in a different script (duplicating a lot of tedious code),
this only implements the required ones (api-key, type and ID) and keeps the rest for later use.
This *scraper* has very limited code that first checks whether we're in playlists mode (`--indiv-playlists` – open to suggestions for a better arg name!) and if not, directly calls youtube2zim.
When in playlists mode, after checking the credentials, it extracts the list of playlists using the same function youtube2zim uses and run youtube2zim for each of them.
Main differences:
- This script is usable as a replacement of the docker command as it handles both regular and playlists request ; a requirement for the zimfarm which supports only a single …
=> Fixed #93: Support all playlists as individual zims

CHANGELOG, README.md, youtube2zim/entrypoint.py, youtube2zim/playlists/entrypoint.py, youtube2zim/playlists/scraper.py, youtube2zim/scraper.py, youtube2zim/utils.py
This fixes #101 by using a temporary directory as build dir by default, and passing --output directly to youtube2zim in playlists mode. Also, a new option --build-dir is introduced for custom build dir location.
=> Use temporary build_dir

CHANGELOG, requirements.txt, youtube2zim/processing.py
Set this to true explicitly to avoid confusions in the future and removes convert_thumbnail in favour of convert_image() from zimscraperlib
=> Add new scraperlib features

requirements.txt, youtube2zim/scraper.py, youtube2zim/templates/article.html, youtube2zim/templates/home.html
Obviously depends on the merging and release of https://github.com/openzim/python_scraperlib/pull/31
- Use the new `make_zim_file` and get rid of the ZimInfo
- [unrelated] Also move the encoding meta in templates as it's annoying (see commit)
=> Use new zim API from zimscraperlib

CHANGELOG, youtube2zim/constants.py, youtube2zim/scraper.py, youtube2zim/templates/article.html, youtube2zim/templates/assets/app.js
This fixes #112 and has some other subtitle related fixes as follows -
- Fix the namespace for subtitles path in app.js - Subtitles for the main video on the homepage were never loaded, due to incorrect path
- Fix crash on iw (Hebrew) subtitles - Apparently `iw` is not iso-639-1 code. The correct code is `he`. See https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes#HE
- Fix subtitles not showing in article page - Due to incorrect attributes being looked by Jinja2
- Fix subtitle display names and change them to `<native name> - <english name>` - `get_subtitles()` now returns only code and display names as a list of dictionaries.
=> Fix subtitles display and prevent crash on Hebrew subtitles

CHANGELOG, get_js_deps.sh, requirements.txt, youtube2zim/processing.py, youtube2zim/scraper.py, youtube2zim/templates/article.html, youtube2zim/templates/assets/app.js, youtube2zim/templates/home.html, youtube2zim/youtube.py
This allows using WebP for thumbnails with optimization and S3 cache support. Also applies the same CSS tweaks (alongwith webp-hero) and fixes #91 as a result.
This does the following chages -
- thumbnail convertion logic is moved from `processing.py` to `download_video_files_batch()` in `scraper.py ` in the form of a function `process_thumbnail()`.
- templates are updated to use WebP thumbnails
- thumbnails are now optimized and uploaded to cache
=> Use WebP for thumbnails and fix seeking on apple browsers

Dockerfile, pyproject.toml, src/youtube2zim/playlists/scraper.py
- we should release a 2.2.0 asap with current `main` status since this would solve #184 (which is blocking all scrapers) but:
- there is a strange error about `metadata_from` when running the scraper with `youtube2zim-playlists` ; it is obviously harmless to simply disable this code since it is not possible to setup the `metadata_from` which current code anyway
- `main` is in fact not correct, it is using Python 3.11 while we are still at `zimscraperlib` 2.0 which supports only Python 3.10 (don't know why this is not causing a problem in Docker build + why it does not raised a red flag before)
- set `metadata_from` to always be `None` for now
- rollback to Python 3.10
- align `zimscraperlib` version constraints in hatch dependencies with project version (just in case)
=> Unset `metadata_from` + rollback to Python 3.10

CHANGELOG, scraper/src/youtube2zim/entrypoint.py, scraper/src/youtube2zim/scraper.py
This PR removes the `--locale` argument from entrypoint.py and some code from scraper.py using the `setlocale` method.
- Closes #226
=> Finish removal of locale related code

CHANGELOG, scraper/src/youtube2zim/schemas.py, scraper/src/youtube2zim/scraper.py, zimui/cypress/e2e/video_player_page.cy.ts, zimui/cypress/fixtures/channel/videos/timelapse-9Tgo.json, zimui/package.json, zimui/src/App.vue, zimui/src/assets/vjs-youtube.css, zimui/src/components/video/VideoPlayer.vue, zimui/src/components/video/player/VideoChannelInfo.vue, zimui/src/components/video/player/VideoDescription.vue, zimui/src/components/video/player/VideoTitleInfo.vue, zimui/src/plugins/webp-hero.ts, zimui/src/types/Channel.ts, zimui/src/views/VideoPlayerView.vue, zimui/yarn.lock
This PR adds the video player for the new UI.
- Set up video.js with support for subtitles and variable playback rates.
- Added `channel_description` and `channel_joined_date` to the `Author` schema so that we can display channel information easily in the video player page.
- Included `webp-hero` for WebP support in unsupported browsers.
- Added a Cypress test for video player page.
`Note:` ogv.js has not been setup yet. I've created #230 to track it seperately.
Closes #215
Closes #174
=> Add Video player page

.github/workflows/Tests.yml, .pre-commit-config.yaml, CHANGELOG, README.md, pyproject.toml, tasks.py
Partial implementation of #235 
- partial because this PR is an update on the `v2` branch since v3 is not yet ready
- this also needs to be backported to `main` branch as well
- tests done
- run again the scraper => all videos are reencoded with VP9 and reuploaded to cache
- run again the scraper a second time => all videos are downloaded from cache and are encoded with VP9
- also implement bootstrap v1.0.2 (fixes to code coverage upload)
=> Upgrade to scraperlib v3.4.0 to use VP9

CHANGELOG, zimui/cypress/e2e/video_player_page.cy.ts, zimui/cypress/fixtures/channel/playlists/timelapses-QgGI.json, zimui/cypress/fixtures/channel/videos/cloudy_sky_time_lapse-k02q.json, zimui/src/components/common/ErrorDisplay.vue, zimui/src/components/playlist/panel/PlaylistPanel.vue, zimui/src/components/playlist/panel/PlaylistPanelItem.vue, zimui/src/components/playlist/panel/PlaylistPanelPreview.vue, zimui/src/components/video/VideoPlayer.vue, zimui/src/components/video/player/VideoChannelInfo.vue, zimui/src/router/index.ts, zimui/src/stores/main.ts, zimui/src/types/Playlists.ts, zimui/src/views/NotFoundView.vue, zimui/src/views/VideoPlayerView.vue
This PR adds a playlist panel to the video player page.
- Added a playlist panel that displays the videos in a playlist (Playlist is loaded through the `list` query parameter in URL)
- Added player control buttons to loop (Loop video/playlist) and shuffle playlist.
- Updated error handling for unknown videos, playlists and paths.
Screenshot:
Closes #216
=> Add playlist panel to video player page

CHANGELOG, zimui/cypress/e2e/playlist_view_page.cy.ts, zimui/cypress/fixtures/channel/playlists/timelapses-QgGI.json, zimui/src/components/playlist/PlaylistCard.vue, zimui/src/components/playlist/panel/PlaylistPanelItem.vue, zimui/src/router/index.ts, zimui/src/views/PlaylistView.vue
Closes #223
Added individual playlist view page that lists all videos from a playlist.
=> Add individual playlist view page

zimui/src/components/channel/AboutDialogButton.vue, zimui/src/components/video/player/VideoDescription.vue, zimui/src/views/PlaylistView.vue
Fix #248
Added the `text-pre-wrap` utility class from Vuetify to render new-lines in description areas in the new UI.
Before:
After:
=> Fix new line rendering in descriptions in zimui

zimui/src/components/channel/ChannelHeader.vue, zimui/src/components/common/ViewInfo.vue, zimui/src/components/playlist/PlaylistGrid.vue, zimui/src/components/playlist/panel/PlaylistPanel.vue, zimui/src/components/video/VideoGrid.vue, zimui/src/views/PlaylistView.vue, zimui/src/views/VideoPlayerView.vue
Changes:
- Fix side margins on tablet screens so that the content fills the entire screen.
- Modify playlist panel height calculation so that the panel fits screen vertically.
Before:
After:
Fix #252
=> Fix side margins on tablet screens in zimui

zimui/src/components/channel/tabs/VideosTab.vue, zimui/src/components/video/VideoCard.vue, zimui/src/components/video/VideoGrid.vue
Close #241
Modified `VideoGrid` and `VideoCard` components to accept a `playlistSlug` prop, so that the playlist panel can be displayed whenever videos from the homepage are played.
=> Display playlist panel for videos played from homepage

scraper/src/youtube2zim/scraper.py
Fix #227 
Replace the `<title>` tag (using RegEx) in index.html of new Vue.js UI to be the ZIM title.
=> Fix title in index.html to be ZIM title

.github/workflows/Publish.yml, .github/workflows/PublishDockerDevImage.yaml, .github/workflows/QA.yml, .github/workflows/Tests.yml
Close #208
Bump Github actions in workflow files. Changes include:
- `actions/checkout@v3` => v4
- `actions/setup-node@v3` => v4
- `actions/setup-python@v4` => v5
- `codecov/codecov-action@v3` => v4
- `pypa/gh-action-pypi-publish@release/v1.8` => 1.9
=> Bump Github actions

CHANGELOG, scraper/src/youtube2zim/entrypoint.py, scraper/src/youtube2zim/schemas.py, scraper/src/youtube2zim/scraper.py
Close #204
Close #209
Changes in this PR:
- Remove `--no-zim` CLI argument.
- Add items "on the fly" to the ZIM:
- Videos and video thumbnails are added to ZIM immediately after they are downloaded.
- Channel branding of main channel (profile.jpg) is added after creating the favicon using it.
- Subtitles are added to ZIM immediately after download. Information about language codes are cached so that it can be used later on to generate JSON files for individual videos.
- Use `validate_zimfile_creatable` from `zimscraperlib` to validate if ZIM cannot be created at given location / name.
- Remove `add_files_to_zim` method from Youtube2Zim class, since we no longer have to copy the whole build directory into the ZIM.
=> Add items to the ZIM "on the fly"

scraper/src/youtube2zim/schemas.py, scraper/src/youtube2zim/scraper.py, zimui/src/components/channel/ChannelHeader.vue, zimui/src/types/Channel.ts
As per the suggestion in https://github.com/openzim/youtube/issues/261#issuecomment-2223121230, the `Playlist` tab in the Vue.js UI can be hidden if there is only 1 playlist in the ZIM. Changes in this PR:
- Add `playlist_count` to channel.json
- Modify `ChannerHeader.vue` to hide the tabs based on the `playlist_count` value.
Screenshot (ZIM with only 1 playlist):
=> Hide playlists tab in `zimui` if there is only 1 playlist

zimui/src/components/channel/AboutDialogButton.vue, zimui/src/components/video/player/VideoChannelInfo.vue
Fix #264
Fix the channel title truncation on smaller screen devices, so that the channel name doesn't break into multiple lines.
Before:
After:
=> Fix channel title truncation for smaller screens in zimui

CHANGELOG, scraper/tests-integration/integration.py
Close #253
- Update `test_zim_scraper` to check more metadata of the ZIM
- Add `test_zim_channel_json` to check contents of `channel.json`
- Add `test_zim_videos` to check existence of video json files, video files, video thumbnails and subtitles.
- Add `test_zim_playlists` to check existence of playlists json files
=> Update integration tests to check content in ZIM

CHANGELOG, zimui/src/views/VideoPlayerView.vue
Close #38
This PR disables the preloading of subtitles in video.js for `zimui`. Changes include:
- Set `preloadTextTracks` as false for both `html5` and `ogvjs` tech plugins.
Tested on `Chrome v127` and `Safari 11.1`
=> Disable preloading of subtitles in video.js

CHANGELOG, scraper/src/youtube2zim/scraper.py, scraper/src/youtube2zim/utils.py
Fix #285
Changes:
- Return `1` whenever a exception is raised.
- Move `self.zim_file.finish()` to an `else` section in the `try-exception` block.
- Move the removal of temp directory and files into the `finally` section  in the `try-exception` block.
- Create `delete_callback` in utils.py since the one in `zimscraperlib.filesystem` does not check for a file's existence before trying to delete it. 
- Whenever an exception is raised there could be callbacks that were already initiated. Since the temp folder gets deleted now, these callbacks would throw an error saying `FileNotFound`. Checking for the existence of the files let's us avoid these errors.
=> Refactor scraper to exit properly when exceptions are raised

zimui/package.json, zimui/yarn.lock
Bump video.js to `v8.17.3` to fix the UI not loading on older Chrome versions. As mentioned in https://github.com/openzim/youtube/issues/275#issuecomment-2277777096 everything works fine in Chrome `v59` and `v58`. 
Close #275
=> Bump video.js to v8.17.3

CHANGELOG, scraper/pyproject.toml, scraper/src/youtube2zim/entrypoint.py, scraper/src/youtube2zim/scraper.py
Close #228
Changes:
- Add new CLI argument `--stats-filename` to specify the path to store the progress JSON file to.
- Add helper function `report_progress` to write the scraper's progress (`done` and `total`) to the specified location in the above CLI argument.
- Schedule `report_progress` to run every 10 seconds.
=> Report scraper progress in a JSON file

CHANGELOG, scraper/src/youtube2zim/youtube.py
Close #286
Changes:
- Replace `list(set(playlist_ids))` to `dict.fromkeys(playlist_ids)` to maintain the order of the given playlist IDs.
=> Fix main playlist selection to respect the order of provided playlist IDs

CHANGELOG, zimui/src/components/channel/ChannelHeader.vue, zimui/src/views/HomeView.vue, zimui/src/views/PlaylistView.vue, zimui/src/views/VideoPlayerView.vue
Fix #298
Fix #299
Changes:
- Update `zimui` title dynamically with the selected playlist/video title.
- Fix PLAYLISTS tab not being highlighted when the page is reloaded.
=> Update zimui HTML page title dynamically with playlist/video title

CHANGELOG, scraper/src/youtube2zim/scraper.py
=> Ignore empty playlists

scraper/src/youtube2zim/scraper.py
Fix #351 
Changes:
- see https://github.com/openzim/youtube/issues/351#issuecomment-2397765106 for details
- it allows to fix bug linked to the fact that we have more often no more merged stream with both video and audio
- it enhances the chances to grab best suited stream(s) before reencoding
=> Enhance yt_dlp format and fix bug

CHANGELOG.md, scraper/src/youtube2zim/schemas.py, scraper/src/youtube2zim/scraper.py, zimui/cypress/e2e/channel_home_page.cy.ts, zimui/cypress/e2e/video_player_page.cy.ts, zimui/cypress/fixtures/channel/home_playlists.json, zimui/package.json, zimui/src/assets/main.css, zimui/src/components/channel/tabs/VideosGridTab.vue, zimui/src/components/channel/tabs/VideosListTab.vue, zimui/src/components/channel/tabs/VideosTab.vue, zimui/src/components/common/ViewInfo.vue, zimui/src/components/video/VideoCard.vue, zimui/src/components/video/VideoList.vue, zimui/src/components/video/carousel/VideoCarousel.vue, zimui/src/components/video/carousel/VideoCarouselInfo.vue, zimui/src/stores/main.ts, zimui/src/types/Playlists.ts, zimui/yarn.lock
Fix #337
Update layout of `Videos` tab in `zimui` to display videos from all playlists in the ZIM. The videos from each playlist are now listed in separate rows as carousels.
Screenshots:
=> Update layout of `Videos` tab in `zimui` to display videos from all playlists in the ZIM

CHANGELOG.md, scraper/src/youtube2zim/scraper.py
Fix #347
Raise exception if there are no videos in the playlists instead of creating an empty ZIM file. 
Tested with this playlist: https://www.youtube.com/playlist?list=PL5glJe_RySVnGr4P1ZCW3Ou32pkz0z-yY
=> Raise exception if there are no videos in the playlists

.github/workflows/Tests.yml, CHANGELOG.md, scraper/src/youtube2zim/scraper.py, scraper/tests-integration/integration.py
Fix #369 
Changes:
- I've also enhanced a bit the integration tests for better checks (even if we can see that we already had a test about `scraper` metadata instead of `Scraper`, so it will not solve the problem we had in this issue at all)
=> Use proper ZIM metadata key for `Scraper` and `Tags`

CHANGELOG.md, scraper/src/youtube2zim/processing.py, scraper/src/youtube2zim/scraper.py
Fix #356
- simplify choosing best format from youtube to be sure to have a format with highest resolution possible in all cases to avoid problems while re-encoding
- always reencode (even for high quality) using our presets, to simplify things (otherwise it is too much dependent on Youtube choices in terms of resolution and codecs and bitrates, hard to follow)
=> Always reencode using our presets (even for high quality) and choose best format

CHANGELOG.md, scraper/src/youtube2zim/scraper.py
Fix #375
Two problems have been fixed:
- scraper was checking the playlist is not empty before filtering by date range, deleted videos, ... => some playlists finally empty were not detected
- scraper was not checking wether the playlist is empty after downloading videos (we could have a majority of videos OK, but all videos of a playlist fails then the playlist is empty
=> Check for empty playlists after filtering, and after downloading videos

CHANGELOG.md, CONTRIBUTING.md, scraper/src/youtube2zim/playlists/scraper.py, scraper/src/youtube2zim/schemas.py, scraper/src/youtube2zim/scraper.py, scraper/src/youtube2zim/youtube.py, scraper/tests-integration/integration.py, zimui/cypress/fixtures/channel/channel.json, zimui/src/assets/main.css, zimui/src/assets/vjs-youtube.css, zimui/src/components/channel/ChannelHeader.vue, zimui/src/components/channel/tabs/ChannelHomeGridTab.vue, zimui/src/components/channel/tabs/ChannelHomeListTab.vue, zimui/src/components/channel/tabs/ChannelHomeTab.vue, zimui/src/components/channel/tabs/GenericTab.vue, zimui/src/components/channel/tabs/LivesTab.vue, zimui/src/components/channel/tabs/PlaylistsTab.vue, zimui/src/components/channel/tabs/ShortsTab.vue, zimui/src/router/index.ts, zimui/src/types/Channel.ts
Replace https://github.com/openzim/youtube/pull/371 to have proper CI operation
Fixes #366 #367
=> Shorts, lives and long videos in the UI + fix shorts display

CHANGELOG.md, scraper/src/youtube2zim/youtube.py
Unlisted videos have to be considered for ZIM inclusion. The fact they are not listed does not means they are not viewable, see e.g. https://www.youtube.com/playlist?list=PL3rEvTTL-Jm-ZIeAfA6U726nsdYaWn4lL ; all videos are unlisted but anyone knowing the playlist will be able to find the video. Unlisted only refers to the fact that it won't come up in search results or be listed on channel home page. Since we explore by playlist ID, we should always include these videos.
=> Unlisted videos must also be included inside the ZIM

CHANGELOG.md, scraper/src/youtube2zim/schemas.py, scraper/src/youtube2zim/scraper.py, zimui/src/assets/vjs-youtube.css, zimui/src/components/video/VideoPlayer.vue, zimui/src/types/Videos.ts, zimui/src/types/videojs.ts, zimui/src/utils/format-utils.ts, zimui/src/views/VideoPlayerView.vue
Fixes #170 
- `yt-dlp` writes a metadata file called `video.info.json` when downloading a video (without an extra yt-dlp call).
- Extract chapters from that metadata file.
- Create a `WEBVTT` file using the chapters.
- Check for `chaptersPath` in `video.json`.
- If found, add a new track called chapter with the `WEBVTT` file.
=> Feat: support video chapters

CHANGELOG.md, zimui/src/assets/vjs-youtube.css, zimui/src/components/video/VideoPlayer.vue, zimui/src/views/VideoPlayerView.vue
Fix #397 
This PR enhances the video player by adding skip **forward/backward** functionality and **keyboard & touch controls** like youtube for a better user experience.
1. `Double-tap left/right` to skip 10s
| **Key(s)**       | **Action**                    |
|------------------|--------------------------------|
| `Shift + N`/ `Shift + n`      | Next video                     |
| `Shift + P` / `Shift + p`     | Previous video                 |
| `Arrow Left`     | Skip **-5s**                   |
| `Shift + Arrow Left` | Go to **previous chapter**  |
| `Arrow Right`    | Skip **+5s**                   |
| `Shift + Arrow Right` | Go to **next chapter**     |
| `Arrow Up`       | Increase volume                |
| `Arrow Down`     | Decrease volume                |
| `Space`          | …
=> Add skip controls & keyboard/touch shortcuts

CHANGELOG.md, zimui/src/assets/vjs-youtube.css, zimui/src/components/video/VideoPlayer.vue, zimui/src/stores/main.ts, zimui/src/views/VideoPlayerView.vue
Fix : #399 
- In case of watching videos on tablet and rotating screen, It'll be better than default and fullscreen modes.
- Also, If you're used to split tablet screen / laptop screen into two parts to open two programs at the same time. You would prefer to put video in theater mode (something between default and fullscreen).
- Use `t` keyboard shortcut to toggle.
=> Add theater mode to video player
